---
name: Delete Obsolete GHCR Images
on:
  workflow_call:
    inputs:
      cut-off:
        type: string
        default: A week ago UTC
        description: The timezone-aware datetime you want to delete container versions that are older than.

permissions: {}
jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete untagged container images according to cut-off
        uses: snok/container-retention-policy@b56f4ff7539c1f94f01e5dc726671cd619aa8072 # v2.2.1
        with:
          image-names: ${{ github.event.repository.name }}
          cut-off: ${{ inputs.cut-off }}
          account-type: org
          org-name: statnett
          untagged-only: true
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
